# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               ECHO
tagline:             'A GPU and Architecture Guy'
description:         'This is the blog for technical notes and shares'
baseurl:             ''
paginate:            5
port:                4444

# About/contact
author:
  name:              Mengchi Zhang
  url:               https://site.google.com/site/mengchizhang
  email:             zhan2308@purdue.edu

# Custom vars
version:             1.0.0
